file:
  directory: D:/mydownload/greengram_ver3

mybatis:
  mapper-locations: mappers/**/*.xml

spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQLDialect
        
  application:
    name: EmailTest5
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      pool-name: HikariPool-1
      max-lifetime: 1800000
      connection-timeout: 30000

    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/greengram_ver3
    username: root
    password: green502
  servlet:
    multipart:
      max-file-size: 15MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ungjae1322@gmail.com
    password: esbrbvglgeadsado
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
